log:
  level: debug
  disable_sentry: true

listener:
  addr: :8000

jwt:
  secret_key: CHANGE_ME_IN_PRODUCTION
  access_expiration_time: 12h
  refresh_expiration_time: 24h

cookies:
  domain: "rarime.com"
  secure: true
  same_site: 4

verifier:
  schema: 12345
  enabled: false